language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install setuptools --upgrade; pip install -r requirements.txt; python setup.py install"
# command to run tests
script: nosetests --with-coverage --cover-package=flask_zappa,bin
after_success:
  coveralls
notifications:
  slack: zappateam:TTJ0mfHunDK0IBweKkEXjGpR
